### ISSUE TITLE
Specify style of the row in case it's included in a form

### ISSUE THREAD

**Issue by Niaro** [Mindfor/fresh-css#15]
I presume this may looks something like this:
```LESS
.row{
	margin-bottom: 1em;
	[class|='col'] {
		padding-right: 1em;
		&:last-child {
			padding-right: 0;
		}
	}
}
```
